WIP: Add app store
ita-social-projects/what-front pull request #11
Opened 2020-10-29 17:56 UTC by PavelKundenko

#### Do not merge until webpack skeleton merge

### Additions

- Redux, react-redux, redux-thunk packages were added
- Store and root reducer were configured
- Redux devtools added 
- Test component(example) was added

Test component: 
![image](https://user-images.githubusercontent.com/47292994/97611814-54908d80-1a1f-11eb-89cf-1f926e38bb17.png)

This pr closes #7

2020-10-29 18:23 UTC, Icemandov approved these changes

2020-10-30 16:00 UTC, sarhan-azizov commented on src/features/test-feature/redux/test-actions.js
> +export const addOne = () => ({
```suggestion
export const addOne = dispatch => () => dispatch({
  type: testActionTypes.ADD_ONE
});
```

2020-10-30 16:05 UTC, sarhan-azizov requested changes

2020-10-30 16:05 UTC, sarhan-azizov commented on src/features/test-feature/index.js
> +import { TestFeature } from './test-feature';
```suggestion
export { TestFeature } from './test-feature';
export { addOne, subtractOne } from './redux/test-actions';
export { counterSelector } from './redux/test-selectors';
```

2020-10-31 16:56 UTC, sarhan-azizov approved these changes

2020-10-31 16:57 UTC, merged