added new readme
ita-social-projects/what-front pull request #12
Opened 2020-10-30 10:13 UTC by Icemandov

close #3

2020-10-30 12:15 UTC, MozdolevskyiMaksym approved these changes

2020-10-30 12:16 UTC, PavelKundenko approved these changes

2020-10-30 12:16 UTC, Anastasiia0999 approved these changes

2020-10-30 12:50 UTC, so2niko approved these changes

2020-10-31 17:28 UTC, sarhan-azizov commented
let's take like a source this one example https://github.com/Jayser/redux-boilerplate

2020-10-31 17:29 UTC, sarhan-azizov requested changes
let's take like a source this one example https://github.com/Jayser/redux-boilerplate

2020-11-02 10:51 UTC, Winchestery approved these changes

2020-11-04 12:40 UTC, so2niko requested changes

2020-11-04 12:40 UTC, so2niko commented on README.md
> +  - Branch name format: `surname-#issue-name_of_issue`
Please edit like this:
`[surname]-[#_of_issue]-[name_of_issue]`
and add example:
`drozdov-3-project_documentation`

2020-11-05 08:52 UTC, sarhan-azizov approved these changes

2020-11-05 08:53 UTC, merged