Added CSS-modules
ita-social-projects/what-front pull request #15
Opened 2020-11-01 19:54 UTC by iklopov

**Added:** 
style-loader;
css-loader;
postcss-loader;
sass-loader.
**Added file:**
postcss.config.js
**Files that added for testing modules:**
color.css;
button.css.

2020-11-05 07:29 UTC, sarhan-azizov requested changes

2020-11-05 07:29 UTC, sarhan-azizov commented on src/features/counter/counter.js
> +import styles from "./Button.css";
```suggestion
import styles from "./button.css";
```

2020-11-05 07:29 UTC, sarhan-azizov commented on src/features/counter/button.css
> +@value colors: "../../colors.css";
@import '../scss/theme';

the folder structure of the styles folder
![image](https://user-images.githubusercontent.com/33009215/98209756-2a236080-1f48-11eb-805d-d9635cf55c27.png)

2020-11-05 08:28 UTC, sarhan-azizov requested changes

2020-11-05 08:28 UTC, sarhan-azizov commented on src/colors.css
> +@value customBlue: #0c77f8;
```suggestion
$customBlue: #0c77f8;
```

2020-11-06 13:27 UTC, Icemandov approved these changes

2020-11-08 11:29 UTC, MozdolevskyiMaksym approved these changes

2020-11-09 17:44 UTC, sarhan-azizov approved these changes

2020-11-10 08:36 UTC, sarhan-azizov approved these changes

2020-11-10 08:36 UTC, merged