Rusynov 5 webpack config
ita-social-projects/what-front pull request #154
Opened 2020-11-22 23:19 UTC by archontis-cpu

# Rebuild webpack config for development and production modes
## New features
- HotModuleReplacement
- Treeshaking
- Production bundle analyzing
- ESLint parsing imported .js and its table reports via console
- Aliases to the source folder:
```
'@'           -> './src'
'@utils'      -> './src/utils'
'@assets'     -> './src/assets'
'@styles'     -> './src/styles'
'@shared'     -> './src/shared'
'@models'     -> './src/models'
'@screens'    -> './src/screens'
'@features'   -> './src/screens'
'@components' -> './src/components'
```

## Changes
- icon.js: Minor changes, previous implementation could work only in-dev mode. Changed path to `*.svg` and attribute `href` from deprecated  `xlink:href`. Now it should work fine in production mode.
- .eslintignore: added node_modules and dist folders.
- .eslintrc.js: turned off rule `import/no-extraneous-dependencies`. The reason is unexpected behavior with this rule in webpack.*.js files. 
- jsconfig.json is a descendant of [tsconfig.json with enabled `allowJs` setting](https://code.visualstudio.com/docs/languages/jsconfig). Created to help IDE (VSCode & WebStrom) resolving paths when aliases used.
- index.html: removed link to bootstrap. We don't need that anymore.
- babelrc: removed `react-css-modules`. We already use CSS modules. 
- assets/*: created the new folder in the sources for images, fonts, and svg. Moved svg folder to assets. It wouldn't affect any component that uses icons, due to paths defined in `icon.js`. This folder will be copied to the build.

2020-11-23 09:22 UTC, PavelKundenko approved these changes

2020-11-23 10:25 UTC, Icemandov approved these changes

2020-11-23 12:17 UTC, MarinaPasternak approved these changes

2020-11-23 15:55 UTC, Winchestery approved these changes

2020-11-23 23:08 UTC, MozdolevskyiMaksym approved these changes

2020-11-24 08:30 UTC, sarhan-azizov requested changes

2020-11-24 08:30 UTC, sarhan-azizov commented on config/paths.js
> +    shared: getSourcePath('shared'),
?

2020-11-24 08:51 UTC, sarhan-azizov approved these changes

2020-11-24 09:19 UTC, Anastasiia0999 approved these changes

2020-11-24 09:48 UTC, so2niko approved these changes

2020-11-24 10:00 UTC, merged