Added api service
ita-social-projects/what-front pull request #160
Opened 2020-11-23 22:11 UTC by PavelKundenko

## Summary of [issue](https://github.com/ita-social-projects/what-front/issues/155)
Create a class, e.g. Service, with methods for getting data / sending

This PR closes #155 
## Summary of change

Added API Service class that contains static methods for each endpoint

2020-11-23 23:35 UTC, archontis-cpu approved these changes

2020-11-24 08:26 UTC, sarhan-azizov requested changes

2020-11-24 08:26 UTC, sarhan-azizov commented on src/utils/ApiService/ApiService.js
> +      reqHeaders.Authorization = `Bearer ${jwt}`;
could u please use axios interceptors for this ?

2020-11-24 08:26 UTC, sarhan-azizov commented on src/utils/ApiService/ApiService.js
> +  static addCourse = (jwt, courseData) => ApiService.sendRequest(`${ApiConfig.BASE_URL}${ApiConfig.COURSES_URL}`, 'POST', jwt, courseData);
these should be in redux action creators

2020-11-24 08:26 UTC, sarhan-azizov commented on src/utils/ApiService/config.js
> +  BASE_URL: 'http://localhost:3000',
```suggestion
  BASE_URL: 'http://localhost:3000/api',
```

2020-11-24 08:26 UTC, sarhan-azizov commented on src/utils/ApiService/config.js
> +  STUDENT_LESSONS_URL: '/api/lessons/students',
I don't see a reason for these constants, do you?

2020-11-24 09:22 UTC, Icemandov approved these changes

2020-11-24 09:23 UTC, Anastasiia0999 approved these changes

2020-11-24 09:54 UTC, so2niko approved these changes

2020-12-01 10:39 UTC, sarhan-azizov approved these changes

2020-12-01 11:12 UTC, merged