Courses model
ita-social-projects/what-front pull request #187
Opened 2020-12-01 13:25 UTC by MozdolevskyiMaksym

### I have created courses model.
We can use actions to:

1. Load courses(Get method), 
2. Create a new course(Post method) 
3. Edit a course(Put method)

2020-12-02 20:13 UTC, PavelKundenko approved these changes

2020-12-02 20:13 UTC, PavelKundenko commented on src/models/courses/sagas.js
> +  yield takeLatest(actionTypes.CREATE_COURSE, createCourseWorker);
Better use takeEvery here

2020-12-02 20:13 UTC, PavelKundenko commented on src/models/courses/sagas.js
> +  yield takeLatest(actionTypes.EDIT_COURSE, editCourseWorker);
Better use takeEvery here

2020-12-03 16:22 UTC, Icemandov approved these changes

2020-12-03 17:47 UTC, Anastasiia0999 requested changes

2020-12-03 17:47 UTC, Anastasiia0999 commented on src/models/courses/reducer.js
> +  data: null,
data: []

2020-12-03 19:57 UTC, Anastasiia0999 approved these changes

2020-12-03 23:45 UTC, archontis-cpu approved these changes

2020-12-04 08:36 UTC, sarhan-azizov approved these changes

2020-12-04 08:36 UTC, sarhan-azizov commented on src/models/index.js
>  export { ApiService } from './api-service/index.js';
this is should be a part of shared folder

2020-12-04 08:36 UTC, sarhan-azizov commented on src/models/index.js
> +export {
let's discuss this

2020-12-04 08:46 UTC, sarhan-azizov approved these changes

2020-12-04 13:20 UTC, Winchestery approved these changes

2020-12-07 11:10 UTC, merged