Protected route component
ita-social-projects/what-front pull request #234
Opened 2020-12-10 16:35 UTC by PavelKundenko

##  [Issue](https://github.com/ita-social-projects/what-front/issues/233)

This PR closes #223 

## Summary of change

Protected route was added:
- unauthorized user redirects to auth page;
- if the user has an inappropriate role for a particular route, the user redirects to the "404" page.

> Accepts 1 required property: 
- **roles**: `array<number>` - list of roles who can access this route

All other props are passed to the inner `Route` component.

2020-12-10 17:09 UTC, Icemandov approved these changes

2020-12-11 12:16 UTC, archontis-cpu approved these changes

2020-12-14 09:07 UTC, MozdolevskyiMaksym approved these changes

2020-12-14 12:07 UTC, sarhan-azizov requested changes

2020-12-14 12:07 UTC, sarhan-azizov commented on src/shared/routes/paths.js
> +export const AUTH = '/auth';
I think this is redundant

2020-12-17 08:36 UTC, sarhan-azizov approved these changes

2020-12-17 14:28 UTC, merged