add role
ita-social-projects/what-front pull request #236
Opened 2020-12-13 16:01 UTC by MarinaPasternak

Conected account model to list of unassigned users feature;
roles in selector depends on role number in the cookie:
add search:
![photo_2020-12-13_18-50-18](https://user-images.githubusercontent.com/31963187/102017012-3a173700-3d75-11eb-8542-e14439b9e4d9.jpg)

2020-12-13 17:39 UTC, PavelKundenko requested changes

2020-12-13 17:39 UTC, PavelKundenko commented on src/features/list-of-courses/courses-data-list.js
> +  },
Remove this file

2020-12-13 17:39 UTC, PavelKundenko commented on src/app.js
> +    <UnAssignedList />
Remove component from App. Add it to the routes.

2020-12-13 17:39 UTC, PavelKundenko commented on src/features/list-of-students/students-dataList.js
> +  {
Remove this file

2020-12-13 17:39 UTC, PavelKundenko commented on src/features/unassigned-list/unassigned-list.js
> +  const currentUserRole = JSON.parse(Cookie.get('user') ?? null).role;
Use current user selector instead of accessing cookies directly.

2020-12-13 17:39 UTC, PavelKundenko commented on src/features/unassigned-list/unassigned-list.js
> +  const roles = ['student', 'mentor', 'secretery'];
*secretary

2020-12-13 17:39 UTC, PavelKundenko commented on src/features/unassigned-list/unassigned-list.js
> +            <p>{`${user.firstName} ${user.lastName}`}<br />{user.email}</p>
No need to use template strings, you can simplify: 
`<p>{user.firstName} {user.lastName}<br />{user.email}</p>`

2020-12-13 17:39 UTC, PavelKundenko commented on src/models/api-service/api-service.js
> +export class ApiService {
Api service should be placed in shared directory

2020-12-13 17:39 UTC, PavelKundenko commented on src/models/mentors/action-types.js
> +export const LOADING_MENTORS_FAILED = 'MENTORS/LOADING_FAILED';
Remove this file

2020-12-14 10:54 UTC, sarhan-azizov approved these changes

2020-12-14 10:56 UTC, MozdolevskyiMaksym approved these changes

2020-12-14 12:51 UTC, Icemandov approved these changes

2020-12-14 12:56 UTC, PavelKundenko approved these changes

2020-12-14 13:13 UTC, merged