Split groups reducer
ita-social-projects/what-front pull request #258
Opened 2020-12-15 13:22 UTC by archontis-cpu

2020-12-15 20:20 UTC, MozdolevskyiMaksym requested changes

2020-12-15 20:20 UTC, MozdolevskyiMaksym commented on src/models/student-groups/selector.js
>  export const studentGroupsSelector = (state) => state.models.studentGroups;
Remove this selector please

2020-12-15 20:20 UTC, MozdolevskyiMaksym commented on src/models/student-groups/reducers/load-groups-reducer.js
> +  groups: [],
Please, rename to data: [] in all reducers

2020-12-17 08:39 UTC, sarhan-azizov approved these changes

2020-12-17 23:18 UTC, PavelKundenko approved these changes

2020-12-18 11:32 UTC, MozdolevskyiMaksym approved these changes

2020-12-18 12:15 UTC, so2niko approved these changes

2020-12-22 22:09 UTC, merged