Support Layout
ita-social-projects/what-front pull request #36
Opened 2020-11-03 20:08 UTC by Anastasiia0999

**Support Layout for connection with secretary**

- **Mockup**
![image](https://user-images.githubusercontent.com/55295369/98035017-87bc8d80-1e20-11eb-9f06-5b00825815e8.png)

- **Result**
![image](https://user-images.githubusercontent.com/55295369/98035109-ac186a00-1e20-11eb-88af-b3aa5424c15b.png)

2020-11-04 13:18 UTC, PavelKundenko approved these changes

2020-11-04 22:03 UTC, MozdolevskyiMaksym approved these changes

2020-11-05 07:05 UTC, sarhan-azizov requested changes

2020-11-05 07:05 UTC, sarhan-azizov commented on src/app.js
>  import { Counter } from './features';
```suggestion
import { Counter, Support } from './features';
```

2020-11-05 10:03 UTC, Winchestery approved these changes

2020-11-05 10:17 UTC, sarhan-azizov approved these changes

2020-11-05 10:17 UTC, merged