Fixed animation of sidebar
ita-social-projects/what-front pull request #510
Opened 2021-01-28 16:40 UTC by VladyslavPolushyn

Fix a bug where the sidebar link's text is visible under the icons.

2021-01-28 21:30 UTC, MozdolevskyiMaksym requested changes

2021-01-28 21:30 UTC, MozdolevskyiMaksym commented on src/features/sidebar/sidebar.js
> +              // onClick={toggleSidebar}
The same

2021-02-03 13:42 UTC, R0D1N approved these changes

2021-02-04 12:25 UTC, Icemandov approved these changes

2021-02-04 12:27 UTC, merged