Kundenko 61 search input component
ita-social-projects/what-front pull request #80
Opened 2020-11-11 22:10 UTC by PavelKundenko

## Summary of [issue](https://github.com/ita-social-projects/what-front/issues/61)
Mock: 
![image](https://user-images.githubusercontent.com/47292994/98868167-6559ee00-2478-11eb-909c-52d3fe50072b.png)

[Wiki](https://github.com/ita-social-projects/what-front/wiki/Search-Input-separated-reusable-component)

This PR
closes #61 

## Summary of change

### Created reusable search input that:
> Accepts 3 required props: 
  - **onSearch**: ` func` - search button click handler
  - **inputRef**: `ref` - react ref that you can use to get input value
  - **placeholder**: `string` - input placeholder
> Accepts 2 optional props: 
  - **onChange**:  `func` - input change handler
  - **additionalCssClasses**: `array<string>` - additional classes that you can apply search container Default: _[ ]_

### Examples: 
```
const inputRef = useRef();

...

<Search
   onSearch={handleSearch}
   inputRef={searchRef}
   placeholder="Search something"
 />
```
![image](https://user-images.githubusercontent.com/47292994/98869668-d3071980-247a-11eb-8b8f-5016f1224c97.png)

2020-11-12 08:55 UTC, sarhan-azizov requested changes

2020-11-12 08:55 UTC, sarhan-azizov commented on src/components/search/search.js
> +  additionalCssClasses,
?
```suggestion
  className,
```

2020-11-12 08:55 UTC, sarhan-azizov commented on src/components/search/search.js
> +      className={styles.search__input}
styles.search__input

styles.searchInput

styles.field

2020-11-12 08:55 UTC, sarhan-azizov commented on src/components/search/search.js
> +  onSearch: PropTypes.func.isRequired,
```suggestion
  onSearch: PropTypes.func.isRequired,
```

func.isRequired,

2020-11-12 08:55 UTC, sarhan-azizov commented on src/components/search/search.js
> +  onChange: () => false,
```suggestion
  onChange:undefined,
```

2020-11-12 08:55 UTC, sarhan-azizov commented on src/features/counter/counter.js
> +    console.log(`Search value = ${searchRef.current.value}`);
this.props.onSearch(searchRef.current.value)

2020-11-12 08:55 UTC, sarhan-azizov commented on src/components/search/search.js
> +  inputRef,
?

2020-11-12 08:55 UTC, sarhan-azizov commented on src/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorig
?

2020-11-12 18:45 UTC, MozdolevskyiMaksym commented on src/components/search/search.js
> +import styles from './search.module.scss';
`'./search.scss'`

2020-11-12 20:05 UTC, MozdolevskyiMaksym approved these changes

2020-11-16 08:12 UTC, sarhan-azizov approved these changes

2020-11-16 08:12 UTC, merged