Tabs reusable component
ita-social-projects/what-front pull request #86
Opened 2020-11-12 19:56 UTC by MozdolevskyiMaksym

I have created Tabs Component, which should accepts 2 properties:

1. Array of objects(your tabs)
2. link that takes us to previous page

[Wiki](https://github.com/ita-social-projects/what-front/wiki/Page-Tabs-separated-reusable-component)

Example of usage
![example of using](https://user-images.githubusercontent.com/72501713/98988122-399e3d00-2538-11eb-8fdd-e5c4b864dee6.png)

Results:
![Tabs-active](https://user-images.githubusercontent.com/72501713/98988214-5cc8ec80-2538-11eb-953e-781eae4a6959.png)

2020-11-12 21:02 UTC, Winchestery approved these changes

2020-11-13 13:30 UTC, Anastasiia0999 approved these changes

2020-11-16 08:09 UTC, sarhan-azizov requested changes

2020-11-16 08:09 UTC, sarhan-azizov commented on src/components/Tabs/tabs.js
> +  tabs: propTypes.arrayOf(propTypes.shape({
Tabs components should include not only tab titles, but also it should has tab's content

2020-11-18 08:05 UTC, sarhan-azizov approved these changes

2020-11-18 08:06 UTC, sarhan-azizov requested changes
let's check together

2020-11-23 23:40 UTC, archontis-cpu approved these changes

2020-11-24 08:12 UTC, sarhan-azizov approved these changes

2020-11-24 09:15 UTC, Anastasiia0999 approved these changes

2020-11-24 09:15 UTC, PavelKundenko approved these changes

2020-11-24 09:22 UTC, so2niko approved these changes

2020-11-24 09:23 UTC, Winchestery approved these changes

2020-11-24 09:26 UTC, merged