feat(events): add events model
ita-social-projects/what-front pull request #863
Opened 2021-12-07 09:52 UTC by serhii-devrel

2021-12-07 20:15 UTC, vitaliymig approved these changes

2021-12-08 16:04 UTC, AntonRufus submitted a review, later dismissed

2021-12-13 08:01 UTC, MariaMatvienko submitted a review, later dismissed

2021-12-13 08:01 UTC, AntonRufus submitted a review, later dismissed

2021-12-13 08:29 UTC, vitaliymig submitted a review, later dismissed

2021-12-20 14:31 UTC, AntonRufus approved these changes

2021-12-22 10:48 UTC, vitaliymig approved these changes

2022-01-25 20:30 UTC, RomanVishnevetskyi approved these changes

2022-02-04 10:07 UTC, sarhan-azizov requested changes
Deployment has failed

2022-02-22 14:15 UTC, merged